import smtplib
import pandas as pd
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

# Config
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
SENDER_EMAIL = "arcot22218@gmail.com"
SENDER_PASSWORD = "Plmokn@9121"  # Use app password or real password if less secure apps enabled
RECIPIENT_EMAIL = "compliance_team@example.com"
RISK_THRESHOLD = 75

# Load audit report
df = pd.read_csv("ai_audit_risk_report.csv")

# Filter high-risk docs
high_risk = df[df["risk_score"] >= RISK_THRESHOLD]

if high_risk.empty:
    print("No high-risk documents to alert.")
else:
    # Create email content
    subject = f"AI Audit Alert: {len(high_risk)} High-Risk Documents Detected"
    body = "The following documents have high risk scores:\n\n"
    
    for _, row in high_risk.iterrows():
        violations = ", ".join(eval(row["violations"])) if row["violations"] != "[]" else "None"
        body += (f"- Doc ID: {row['doc_id']}\n"
                 f"  Generated By: {row['generated_by']}\n"
                 f"  User: {row['ai_user_id']}\n"
                 f"  Risk Score: {row['risk_score']}\n"
                 f"  Violations: {violations}\n\n")
    
    # Setup MIME
    msg = MIMEMultipart()
    msg['From'] = SENDER_EMAIL
    msg['To'] = RECIPIENT_EMAIL
    msg['Subject'] = subject
    msg.attach(MIMEText(body, 'plain'))
    
    # Send email
    try:
        server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
        server.starttls()
        server.login(SENDER_EMAIL, SENDER_PASSWORD)
        server.send_message(msg)
        server.quit()
        print("Alert email sent successfully.")
    except Exception as e:
        print(f"Failed to send email: {e}")
