import pandas as pd
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
import matplotlib.pyplot as plt

# Load CSV report
df = pd.read_csv("ai_audit_risk_report.csv")

# Create bar chart of risk scores
plt.figure(figsize=(10, 5))
plt.bar(df["doc_id"], df["risk_score"], color="red")
plt.xlabel("Document ID")
plt.ylabel("Risk Score")
plt.title("AI Audit Risk Scores")
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig("risk_chart.png")
plt.close()

# Create PDF
styles = getSampleStyleSheet()
pdf = SimpleDocTemplate("AI_Audit_Report.pdf", pagesize=LETTER)
elements = []

title = Paragraph("AI Audit Risk Report", styles['Title'])
elements.append(title)
elements.append(Spacer(1, 12))

# Add summary table (first 10 entries)
data = [["Doc ID", "Generated By", "User", "Violations", "Risk Score"]]
for _, row in df.head(10).iterrows():
    data.append([
        row["doc_id"],
        row["generated_by"],
        str(row["ai_user_id"]) if pd.notna(row["ai_user_id"]) else "N/A",
        ", ".join(eval(row["violations"])) if row["violations"] != "[]" else "-",
        row["risk_score"]
    ])

table = Table(data, hAlign='LEFT')
table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), colors.lightgrey),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.black),
    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold')
]))
elements.append(table)
elements.append(Spacer(1, 24))

# Add chart image
from reportlab.platypus import Image
elements.append(Paragraph("Risk Score Chart", styles['Heading2']))
elements.append(Spacer(1, 6))
elements.append(Image("risk_chart.png", width=450, height=250))

# Build PDF
pdf.build(elements)
print("PDF report generated: AI_Audit_Report.pdf")
